# Html5BoilerplateHelper will first check your ENV and
# then this yml file for these values. If they are both
# empty, the google code block will not be used.
#
# e.g. ENV['GOOGLE_ACCOUNT_ID'] || yml[:google_account_id]
# e.g. ENV['GOOGLE_API_KEY'] || yml[:google_api_key]
#
defaults: &defaults
  :google_account_id: 'UA-3202633-11'
  :google_api_key: 'ABQIAAAA9i9eJP3lvywadcKyDIwkERQlz6gKE934j5Ic5I_au0KOK-1rERTIQfB0p_qPaW_NRK2fPaiJfv154Q'

:development:
  <<: *defaults

:test:
  <<: *defaults

:staging:
  <<: *defaults

:production:
  <<: *defaults
